# Chat Project Config

# Make sure the plugins belonging to this project type are loaded
plugins.includedPluginPaths: ['x-pack/solutions/chat']

## Enable the Serverless Chat plugin
xpack.serverless.chat.enabled: true

## Cloud settings
xpack.cloud.serverless.project_type: search

## Set the home route
uiSettings.overrides.defaultRoute: /app/home
